# Support Vector Machine (SVM)

# Importing the libraries

In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing Dataset

In [49]:
dataset = pd.read_csv('Iris.csv', index_col=0)
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [50]:
print(dataset)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  I

# Splitting the Dataset into training and test set

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [52]:
print(X_train)

[[3.  4.2 1.5]
 [2.6 4.  1.2]
 [3.  5.5 2.1]
 [3.2 1.3 0.2]
 [3.1 5.1 2.3]
 [3.5 1.6 0.6]
 [3.7 1.5 0.2]
 [2.  3.5 1. ]
 [3.  5.5 1.8]
 [3.3 5.7 2.5]
 [2.2 5.  1.5]
 [2.5 5.8 1.8]
 [2.5 3.9 1.1]
 [3.  6.1 2.3]
 [3.3 4.7 1.6]
 [2.4 3.8 1.1]
 [2.7 4.9 1.8]
 [2.8 5.1 1.5]
 [2.5 4.5 1.7]
 [2.5 5.  1.9]
 [3.2 4.7 1.4]
 [3.  5.2 2. ]
 [3.4 4.5 1.6]
 [3.1 1.6 0.2]
 [2.7 5.1 1.9]
 [2.7 4.2 1.3]
 [2.9 3.6 1.3]
 [2.5 4.  1.3]
 [3.  4.6 1.4]
 [3.2 6.  1.8]
 [3.7 1.5 0.2]
 [3.  1.1 0.1]
 [2.7 5.3 1.9]
 [3.  4.2 1.2]
 [3.4 1.7 0.2]
 [4.4 1.5 0.4]
 [3.1 4.9 1.5]
 [3.1 1.5 0.2]
 [3.  5.1 1.8]
 [2.5 3.  1.1]
 [3.4 1.4 0.3]
 [2.2 4.5 1.5]
 [3.6 6.1 2.5]
 [2.9 4.2 1.3]
 [3.  1.4 0.1]
 [3.  5.9 2.1]
 [3.2 5.7 2.3]
 [3.  5.8 2.2]
 [2.8 5.6 2.1]
 [3.8 1.6 0.2]
 [3.4 1.6 0.2]
 [3.2 5.1 2. ]
 [3.3 5.7 2.1]
 [2.3 1.3 0.3]
 [3.4 5.4 2.3]
 [3.  1.4 0.2]
 [2.5 5.  2. ]
 [3.1 5.4 2.1]
 [3.2 1.3 0.2]
 [3.6 1.4 0.2]
 [3.  5.8 1.6]
 [3.5 1.4 0.3]
 [3.  1.3 0.2]
 [3.9 1.7 0.4]
 [2.3 4.  1.3]
 [3.2 5.9 2.3]
 [3.  6.6 

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [54]:
print(y_train)

[1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0 1
 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2 2 0 0 0 1 1 0 0
 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1 1 1 1 0 0 0 2 1 2
 0]


In [55]:
print(X_test)

[[2.8 5.1 2.4]
 [2.2 4.  1. ]
 [4.2 1.4 0.2]
 [2.9 6.3 1.8]
 [3.4 1.5 0.2]
 [3.3 6.  2.5]
 [3.5 1.3 0.3]
 [3.1 4.7 1.5]
 [2.8 4.8 1.4]
 [2.8 4.  1.3]
 [2.6 5.6 1.4]
 [3.2 4.5 1.5]
 [2.8 4.7 1.2]
 [2.8 4.6 1.5]
 [2.9 4.7 1.4]
 [3.1 1.5 0.1]
 [2.9 4.5 1.5]
 [2.6 4.4 1.2]
 [3.  1.4 0.3]
 [3.9 1.3 0.4]
 [2.8 4.9 2. ]
 [3.  4.5 1.5]
 [3.4 1.9 0.2]
 [2.9 1.4 0.2]
 [2.8 4.8 1.8]
 [3.6 1.  0.2]
 [3.8 1.9 0.4]
 [2.9 4.3 1.3]
 [2.3 3.3 1. ]
 [3.4 1.6 0.4]
 [3.1 5.5 1.8]
 [3.  4.5 1.5]
 [3.5 1.5 0.2]
 [3.  4.9 1.8]
 [2.8 5.6 2.2]
 [2.7 3.9 1.4]
 [3.8 1.7 0.3]
 [2.7 5.1 1.6]]


In [56]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_test = le.fit_transform(y_test)

In [57]:
print(y_test)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


# Feature Scaling

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
print(X_train)

[[-1.19254753e-01  2.25126850e-01  3.56381749e-01]
 [-1.04039491e+00  1.13559562e-01 -2.86480506e-02]
 [-1.19254753e-01  9.50314227e-01  1.12644135e+00]
 [ 3.41315328e-01 -1.39259884e+00 -1.31208072e+00]
 [ 1.11030287e-01  7.27179649e-01  1.38312788e+00]
 [ 1.03217045e+00 -1.22524790e+00 -7.98707650e-01]
 [ 1.49274053e+00 -1.28103155e+00 -1.31208072e+00]
 [-2.42210516e+00 -1.65358660e-01 -2.85334584e-01]
 [-1.19254753e-01  9.50314227e-01  7.41411549e-01]
 [ 5.71600368e-01  1.06188152e+00  1.63981441e+00]
 [-1.96153508e+00  6.71396005e-01  3.56381749e-01]
 [-1.27067995e+00  1.11766516e+00  7.41411549e-01]
 [-1.27067995e+00  5.77759173e-02 -1.56991317e-01]
 [-1.19254753e-01  1.28501609e+00  1.38312788e+00]
 [ 5.71600368e-01  5.04045072e-01  4.84725016e-01]
 [-1.50096499e+00  1.99227301e-03 -1.56991317e-01]
 [-8.10109874e-01  6.15612361e-01  7.41411549e-01]
 [-5.79824834e-01  7.27179649e-01  3.56381749e-01]
 [-1.27067995e+00  3.92477783e-01  6.13068282e-01]
 [-1.27067995e+00  6.71396005e-

In [60]:
print(X_test)

[[-0.57982483  0.72717965  1.51147115]
 [-1.96153508  0.11355956 -0.28533458]
 [ 2.64416573 -1.33681519 -1.31208072]
 [-0.34953979  1.39658338  0.74141155]
 [ 0.80188541 -1.28103155 -1.31208072]
 [ 0.57160037  1.22923245  1.63981441]
 [ 1.03217045 -1.39259884 -1.18373745]
 [ 0.11103029  0.50404507  0.35638175]
 [-0.57982483  0.55982872  0.22803848]
 [-0.57982483  0.11355956  0.09969522]
 [-1.04039491  1.00609787  0.22803848]
 [ 0.34131533  0.39247778  0.35638175]
 [-0.57982483  0.50404507 -0.02864805]
 [-0.57982483  0.44826143  0.35638175]
 [-0.34953979  0.50404507  0.22803848]
 [ 0.11103029 -1.28103155 -1.44042398]
 [-0.34953979  0.39247778  0.35638175]
 [-1.04039491  0.33669414 -0.02864805]
 [-0.11925475 -1.33681519 -1.18373745]
 [ 1.95331061 -1.39259884 -1.05539418]
 [-0.57982483  0.61561236  0.99809808]
 [-0.11925475  0.39247778  0.35638175]
 [ 0.80188541 -1.05789697 -1.31208072]
 [-0.34953979 -1.33681519 -1.31208072]
 [-0.57982483  0.55982872  0.74141155]
 [ 1.26245549 -1.55994977

# Training the SVM model on the Training set

In [61]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# Predicting a new result

# Predicting the Test set results

In [62]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 1]]


# Making the Confusion Matrix

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


0.9736842105263158

# K-Nearest Neighbors (K-NN)

# Importing the libraries

In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing Dataset

In [65]:
dataset = pd.read_csv('Iris.csv', index_col=0)
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [66]:
print(dataset)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  I

# Splitting the dataset into the Training set and Test set

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [68]:
print(X_train)

[[3.  4.2 1.5]
 [2.6 4.  1.2]
 [3.  5.5 2.1]
 [3.2 1.3 0.2]
 [3.1 5.1 2.3]
 [3.5 1.6 0.6]
 [3.7 1.5 0.2]
 [2.  3.5 1. ]
 [3.  5.5 1.8]
 [3.3 5.7 2.5]
 [2.2 5.  1.5]
 [2.5 5.8 1.8]
 [2.5 3.9 1.1]
 [3.  6.1 2.3]
 [3.3 4.7 1.6]
 [2.4 3.8 1.1]
 [2.7 4.9 1.8]
 [2.8 5.1 1.5]
 [2.5 4.5 1.7]
 [2.5 5.  1.9]
 [3.2 4.7 1.4]
 [3.  5.2 2. ]
 [3.4 4.5 1.6]
 [3.1 1.6 0.2]
 [2.7 5.1 1.9]
 [2.7 4.2 1.3]
 [2.9 3.6 1.3]
 [2.5 4.  1.3]
 [3.  4.6 1.4]
 [3.2 6.  1.8]
 [3.7 1.5 0.2]
 [3.  1.1 0.1]
 [2.7 5.3 1.9]
 [3.  4.2 1.2]
 [3.4 1.7 0.2]
 [4.4 1.5 0.4]
 [3.1 4.9 1.5]
 [3.1 1.5 0.2]
 [3.  5.1 1.8]
 [2.5 3.  1.1]
 [3.4 1.4 0.3]
 [2.2 4.5 1.5]
 [3.6 6.1 2.5]
 [2.9 4.2 1.3]
 [3.  1.4 0.1]
 [3.  5.9 2.1]
 [3.2 5.7 2.3]
 [3.  5.8 2.2]
 [2.8 5.6 2.1]
 [3.8 1.6 0.2]
 [3.4 1.6 0.2]
 [3.2 5.1 2. ]
 [3.3 5.7 2.1]
 [2.3 1.3 0.3]
 [3.4 5.4 2.3]
 [3.  1.4 0.2]
 [2.5 5.  2. ]
 [3.1 5.4 2.1]
 [3.2 1.3 0.2]
 [3.6 1.4 0.2]
 [3.  5.8 1.6]
 [3.5 1.4 0.3]
 [3.  1.3 0.2]
 [3.9 1.7 0.4]
 [2.3 4.  1.3]
 [3.2 5.9 2.3]
 [3.  6.6 

In [69]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [70]:
print(y_train)

[1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0 1
 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2 2 0 0 0 1 1 0 0
 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1 1 1 1 0 0 0 2 1 2
 0]


In [71]:
print(X_test)

[[2.8 5.1 2.4]
 [2.2 4.  1. ]
 [4.2 1.4 0.2]
 [2.9 6.3 1.8]
 [3.4 1.5 0.2]
 [3.3 6.  2.5]
 [3.5 1.3 0.3]
 [3.1 4.7 1.5]
 [2.8 4.8 1.4]
 [2.8 4.  1.3]
 [2.6 5.6 1.4]
 [3.2 4.5 1.5]
 [2.8 4.7 1.2]
 [2.8 4.6 1.5]
 [2.9 4.7 1.4]
 [3.1 1.5 0.1]
 [2.9 4.5 1.5]
 [2.6 4.4 1.2]
 [3.  1.4 0.3]
 [3.9 1.3 0.4]
 [2.8 4.9 2. ]
 [3.  4.5 1.5]
 [3.4 1.9 0.2]
 [2.9 1.4 0.2]
 [2.8 4.8 1.8]
 [3.6 1.  0.2]
 [3.8 1.9 0.4]
 [2.9 4.3 1.3]
 [2.3 3.3 1. ]
 [3.4 1.6 0.4]
 [3.1 5.5 1.8]
 [3.  4.5 1.5]
 [3.5 1.5 0.2]
 [3.  4.9 1.8]
 [2.8 5.6 2.2]
 [2.7 3.9 1.4]
 [3.8 1.7 0.3]
 [2.7 5.1 1.6]]


In [72]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_test = le.fit_transform(y_test)

In [73]:
print(y_test)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]


# Feature Scaling

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [75]:
print(X_train)

[[-1.19254753e-01  2.25126850e-01  3.56381749e-01]
 [-1.04039491e+00  1.13559562e-01 -2.86480506e-02]
 [-1.19254753e-01  9.50314227e-01  1.12644135e+00]
 [ 3.41315328e-01 -1.39259884e+00 -1.31208072e+00]
 [ 1.11030287e-01  7.27179649e-01  1.38312788e+00]
 [ 1.03217045e+00 -1.22524790e+00 -7.98707650e-01]
 [ 1.49274053e+00 -1.28103155e+00 -1.31208072e+00]
 [-2.42210516e+00 -1.65358660e-01 -2.85334584e-01]
 [-1.19254753e-01  9.50314227e-01  7.41411549e-01]
 [ 5.71600368e-01  1.06188152e+00  1.63981441e+00]
 [-1.96153508e+00  6.71396005e-01  3.56381749e-01]
 [-1.27067995e+00  1.11766516e+00  7.41411549e-01]
 [-1.27067995e+00  5.77759173e-02 -1.56991317e-01]
 [-1.19254753e-01  1.28501609e+00  1.38312788e+00]
 [ 5.71600368e-01  5.04045072e-01  4.84725016e-01]
 [-1.50096499e+00  1.99227301e-03 -1.56991317e-01]
 [-8.10109874e-01  6.15612361e-01  7.41411549e-01]
 [-5.79824834e-01  7.27179649e-01  3.56381749e-01]
 [-1.27067995e+00  3.92477783e-01  6.13068282e-01]
 [-1.27067995e+00  6.71396005e-

In [76]:
print(X_test)

[[-0.57982483  0.72717965  1.51147115]
 [-1.96153508  0.11355956 -0.28533458]
 [ 2.64416573 -1.33681519 -1.31208072]
 [-0.34953979  1.39658338  0.74141155]
 [ 0.80188541 -1.28103155 -1.31208072]
 [ 0.57160037  1.22923245  1.63981441]
 [ 1.03217045 -1.39259884 -1.18373745]
 [ 0.11103029  0.50404507  0.35638175]
 [-0.57982483  0.55982872  0.22803848]
 [-0.57982483  0.11355956  0.09969522]
 [-1.04039491  1.00609787  0.22803848]
 [ 0.34131533  0.39247778  0.35638175]
 [-0.57982483  0.50404507 -0.02864805]
 [-0.57982483  0.44826143  0.35638175]
 [-0.34953979  0.50404507  0.22803848]
 [ 0.11103029 -1.28103155 -1.44042398]
 [-0.34953979  0.39247778  0.35638175]
 [-1.04039491  0.33669414 -0.02864805]
 [-0.11925475 -1.33681519 -1.18373745]
 [ 1.95331061 -1.39259884 -1.05539418]
 [-0.57982483  0.61561236  0.99809808]
 [-0.11925475  0.39247778  0.35638175]
 [ 0.80188541 -1.05789697 -1.31208072]
 [-0.34953979 -1.33681519 -1.31208072]
 [-0.57982483  0.55982872  0.74141155]
 [ 1.26245549 -1.55994977

# Training the K-NN model on the Training set

In [78]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

# Predicting the Test set results

In [79]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 1]]


# Making the Confusing Matrix

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


0.9736842105263158

# Conclusion: Both the classification algorithms have same accuracy